export const CLIENTS = [
  "BNM Institute of technology",
  "CMR Engineering College",
  "Dayanand Sagar Institutions + (DODE)",
  "Dr.N.G.P. Institute of Technology", 
  "GITAM",
  "GVPEC",
  "J.N.N. Institute of Engineering",
  "JSPM's Jayawantrao Sawant College Of Engineering (JSCOE)",
  "Kakatiya Institute of Technology and Science",
  "Knowledge Institute of Technology",
  "Lovely Professional University",
  "Manipal University, Jaipur",
  "Nandha College of Engineering & Technology",
  "NIIT University",
  "Parul University",
  "Prasad V. Potluri Siddhartha Institute Of Technology",
  "PSG College Of Technology and Institute of Technology",
  "Rajalakshmi Engineering College",
  "RMK",
  "SGT University",
  "Sri Ramakrishna Engineering College",
  "Sri Ramakrishna Institute of Technology",
  "SRM IST",
  "Thiagaraja College Enginnering",
  "Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering &Technology",
  "Vel Tech University, Hightech & MultiTech",
  "VIT AP",
  "VIT Chennai",
  "VIT Softskills - Vellore, chennai, AP",
  "VIT Vellore",
  "Hindusthan Institute of Technology",
  "Mahendra College of Engineering",
  "PSG itech",
  "Noida Institute of Engineering and Technology"
].sort();
